video_webapp/posts/urls.py
from django.urls import path
from .views import (
  PostListView, 
  PostDetailView,
  PostCreateView,
  PostUpdateView,
  PostDeleteView,
  UserPostListView,
)
from . import views

# URL patterns for each type of page
# <...> indicates variable for URL, pk is the key for the post
urlpatterns = [
    path('', PostListView.as_view(), name="posts-home"),
    path('user/<str:username>', UserPostListView.as_view(), name="user-posts"),
    path('<int:pk>/', PostDetailView.as_view(), name="post-detail"),
    path('new/', PostCreateView.as_view(), name="post-create"),
    path('<int:pk>/update/', PostUpdateView.as_view(), name="post-update"),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
]

video_webapp/video_webapp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.views.generic import RedirectView
from users import views as user_views

urlpatterns = [
  path('admin/', admin.site.urls),
  path('register/', user_views.register, name='register'),
  path('profile/', user_views.profile, name='profile'),
  path('login/', user_views.ip_login, name='login'),
  path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
  path('posts/', include('posts.urls')),
  path('', RedirectView.as_view(url='/posts'), name='home'),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video_webapp/posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from PIL import Image

# The Post class is a model for creating genereic posts
# These posts must include a title and content, but
# not a video or video thumbnail
class Post(models.Model):
  title = models.CharField(max_length=100)
  content = models.TextField()
  date_posted = models.DateTimeField(default=timezone.now) # passing in function for timezone
  author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE) # CASCADE will delete post if user is deleted

  # Optional video fields
  # blank means that it is not required on the form when posting
  # null allows the database to not have an entry (i.e. no default)
  video = models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', verbose_name='Video (optional)',
    validators=[FileExtensionValidator(allowed_extensions=['mp4', 'ogb', 'webm'])]) 

  video_thumbnail = models.ImageField(blank=True, default='default_thumbnail.jpg',  verbose_name='Video Thumbnail (optional)',
    upload_to='thumbnails/%Y/%m/%d/')

  # For resizing thumnail
  def save(self, *args, **kwargs):
    # Use the original save first 
    super().save(*args, **kwargs)

    # Resize the thumbnail
    thumbnail = Image.open(self.video_thumbnail.path)
    output_size = (160, 90)
    thumbnail.thumbnail(output_size)
    thumbnail.save(self.video_thumbnail.path)

  # Use title as the string
  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('post-detail', kwargs={'pk': self.pk})

# The comment model is for creating comments within the post model
class Comment(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE)
  author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
  comment = models.TextField(verbose_name=u"")
  date_posted = models.DateTimeField(default=timezone.now)


video_webapp/posts/forms.py
from django import forms
from .models import Comment

class CommentCreationForm(forms.ModelForm):
  # Type of field used in rendered form
  comment = forms.CharField(label="", help_text="", widget=forms.Textarea(attrs={'rows':5,'cols':20, 'style':'resize:none;'}))

  class Meta:
    # Model to save comment as
    model = Comment

    # Fields to display in the rendered form
    fields = ('comment',)

class CommentUpdateForm(forms.ModelForm):
  comment = forms.CharField(label="", help_text="", widget=forms.Textarea(attrs={'rows':5,'cols':20, 'style':'resize:none;'}))

  class Meta:
    model = Comment
    fields = ('comment',)
  
class CommentDeleteForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = []


video_webapp/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import (
  LoginRequiredMixin,
  UserPassesTestMixin
)
from django.contrib.auth import get_user_model 
from django.views.generic.list import MultipleObjectMixin
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.views.generic import (
  ListView, 
  DetailView, 
  CreateView,
  UpdateView,
  DeleteView,
)
from django.contrib import messages
from django.urls import reverse
from .models import Post, Comment
from .forms import CommentCreationForm, CommentDeleteForm, CommentUpdateForm


##########################
# Post Views
##########################

# View for listing multiple posts
class PostListView(ListView):
  model = Post
  
  # This is what it looks for
  # <app>/<model>_<viewtype>.html
  # without below line
  template_name = 'posts/post_home.html'

  # Find object to iterate over
  context_object_name = 'posts'

  # Order of the objects to list
  ordering = ['-date_posted']

  # Determines the number of posts that are displayed on a given page
  # Activates pagination
  paginate_by = 5

# Same as above, but narrowed by user
class UserPostListView(ListView):
  model = Post

  template_name = 'posts/user_posts.html'
  context_object_name = 'posts'
  paginate_by = 5

  # Narrow the query set for displaying only post from a given user
  def get_queryset(self):
    user = get_object_or_404(get_user_model(), username=self.kwargs.get('username'))
    return Post.objects.filter(author=user).order_by('-date_posted')

# View to handle displaying a single post 
# Uses MultipleObjectMixin to allow pagination and FormMixin for forms
class PostDetailView(FormMixin, MultipleObjectMixin, DetailView):
  model = Post
  template_name = 'posts/post_detail.html'
  paginate_by = 5
  form_class = CommentCreationForm # Creation is the default

  # Allows multiple models
  def get_context_data(self, **kwargs):
    # Set list to paginate by (would have defaulted to list of posts)
    object_list = Comment.objects.filter(post=self.get_object()).order_by('-date_posted')

    context = super(PostDetailView, self).get_context_data(object_list=object_list, **kwargs)

    # Create form instances and provide contex for html
    context['comment_form'] = self.get_form(CommentCreationForm)
    context['update_form'] = self.get_form(CommentUpdateForm)
    context['delete_form'] = self.get_form(CommentDeleteForm)
    return context

  def get_success_url(self):
    return reverse('post-detail', kwargs={'pk': self.object.pk})
  
  def post(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      return HttpResponseForbidden()

    self.object = self.get_object() # Needed

    # Create form submitted
    if 'create' in request.POST:
      comment_form = self.get_form(CommentCreationForm)

      if comment_form.is_valid():
        print("Create form submitted")
        # Save without commit give a comment instance
        comment = comment_form.save(commit=False)

        # Tie comment to post it was created on and author
        comment.post = Post.objects.get(pk=kwargs['pk'])
        comment.author = request.user
        messages.success(request, f'Comment Created')
        comment.save()
        return self.form_valid(comment_form)
      else:
        print("Invalid create form")
        return self.form_invalid(comment_form)

    # Update form submitted
    elif 'update' in request.POST:
      # The comment id should have been passed as a key-value pair
      comment_id = request.POST.get('update')
      instance = Comment.objects.get(id=comment_id)
      update_form = CommentUpdateForm(instance=instance, data=request.POST or None)

      if update_form.is_valid():
        print("Update form Submitted")
        update_form.save()
        return self.form_valid(update_form)
      else:
        print("Invalid update form")
        return self.form_valid(update_form)

    # Delete form submitted
    elif 'delete' in request.POST:
      comment_id = request.POST.get('delete')
      instance = Comment.objects.get(id=comment_id)
      delete_form = CommentDeleteForm(instance=instance, data=request.POST or None)

      if delete_form.is_valid():
        print("Delete form submitted")
        instance.delete()
        return self.form_valid(delete_form)
      else:
        print("Invalid delete form")
        return self.form_invalid(delete_form)
    
    # No (known) form submitted
    else:
      print("No matching forms")
      return HttpResponseForbidden()  

class PostCreateView(LoginRequiredMixin, CreateView):
  model = Post
  fields = ['title', 'content', 'video_thumbnail', 'video']

  # Assign the current user as the author
  def form_valid(self, form):
    form.instance.author = self.request.user
    return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
  model = Post
  fields = ['title', 'content']

  # Assign the current user as the author
  def form_valid(self, form):
    form.instance.author = self.request.user
    return super().form_valid(form)

  # This prevents other users from editing posts that aren't theirs
  def test_func(self):
    post = self.get_object()
    if self.request.user == post.author:
      return True
    return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
  model = Post
  success_url = "/" # Where to go after delete succeeds

  def test_func(self):
    post = self.get_object()
    if self.request.user == post.author:
      return True
    return False

video_webapp/posts/templates/posts/base.html
{% extends "posts/shell.html" %}
{% block body %}
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand mr-4" href="/">Local App</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">{{ user }}</a>
                <a href="{% url 'profile' %}">
                  <img src="{{ user.profile.image.url }}" width="40" height="40" class="rounded-circle">
                </a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags}}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        {% block sidebar %}{% endblock %}
        <div class="col-md-1"></div>
      </div>
      {% block video %}{% endblock %}
    </main>
{% endblock body %}

video_webapp/posts/templates/posts/comment_form.html
{% extends "posts/shell.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="fixed-top">
      <div class="row">
        <!--Spacing-->
        <div class="col-md-1"></div>
        <div class="col-md-8">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
              <h3 class=" mb-1">Edit Comment</h3>
              {{ form|crispy }}
            </fieldset>
            <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Post Comment</button>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock body %}

video_webapp/posts/templates/posts/comment_page.html
{% load crispy_forms_tags %}
{% for com in object_list %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ com.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' com.author.username %}">{{ com.author }}</a>
        <small class="text-muted">{{ com.date_posted|date:"l, F dS, Y, P T" }}</small>
      </div>
      <p class="break-words">{{ com.comment }}</p>
      {% if com.author == user %}
      <!--Update and Delete Toggle-->
      <div id='changecomment-toggle-button-{{ com.id }}'>
        <a class="text-muted" type="button" onclick="hideToggleDual('changecomment-toggle-button-{{ com.id }}','updatecomment-toggle-button-{{ com.id }}')">Edit Comment</a>
        |
        <a class="text-muted" type="button" onclick="hideToggleDual('changecomment-toggle-button-{{ com.id }}','deletecomment-toggle-button-{{ com.id }}')">Delete Comment</a>
      </div>

      <!--Update form-->
      <div id='updatecomment-toggle-button-{{ com.id }}' style="display:none">
        <form method="post" class='update-comment-form' value="{{ com.id }}">
          {% csrf_token %}
          {{ update_form|crispy }}
          <button class="btn btn-outline-success" value="{{ com.id }}" type="submit">Confirm Edit</button>
          <a class="btn btn-outline-secondary" onclick="hideToggleDual('changecomment-toggle-button-{{ com.id }}','updatecomment-toggle-button-{{ com.id }}')">Cancel</a>
        </form>
      </div>

      <!--Delete Form-->
      <div id='deletecomment-toggle-button-{{ com.id }}' style="display:none">
        <form method="post" class='delete-comment-form' value="{{ com.id }}">
          {% csrf_token %}
          {{ delete_form|crispy }}
          <button class="btn btn-danger" value="{{ com.id }}" type="submit">Confirm Delete</button>
          <a class="btn btn-outline-secondary" onclick="hideToggleDual('changecomment-toggle-button-{{ com.id }}','deletecomment-toggle-button-{{ com.id }}')">Cancel</a>
        </form>
      </div>
      {% endif %}
    </div>
  </article>
  {% endfor %}
  {% if is_paginated %}
  <span class="comment-pagination">
    <!-- Add prev and first links if not already on first -->
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4 pag-button" name='page' value='1' href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4 pag-button" name='page' value='{{ page_obj.previous_page_number }}' href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    <!-- Add in pages around the current page -->
    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4 pag-button" name='page' value='{{ num }}' href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4 pag-button" name='page' value='{{ num }}' href="?page={{ num }}">{{ num }}</a>    
      {% endif %}
    {% endfor %}

    <!-- Add in the last if not at the end already -->
    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4 pag-button" name='page' value='{{ page_obj.next_page_number }}' href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4 pag-button" name='page' value='{{ page_obj.paginator.num_pages }}' href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
  </span>
  {% endif %}

video_webapp/posts/templates/posts/post_brief.html
{% extends "posts/base.html" %}
{% block content %}
  {% block post %}{% endblock %}
  {% for post in posts %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">{{ post.date_posted|date:"l, F dS, Y, P T" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
        {% if post.video %}
          <a href="{% url 'post-detail' post.id %}">
            <img src="{{ post.video_thumbnail.url }}" width="160" height="90">
          </a>
        {% endif %}
        <p class="article-content break-words">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}
  {% if is_paginated %}

    <!-- Add prev and first links if not already on first -->
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    <!-- Add in pages around the current page -->
    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>    
      {% endif %}
    {% endfor %}

    <!-- Add in the last if not at the end already -->
    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}
{% endblock content %}
{% block sidebar %}
  <div class="col-md-3">
    <div class="content-section">
      <h3>Our Sidebar</h3>
      <p class='text-muted'>You can put any information here you'd like.
        <ul class="list-group">
          <li class="list-group-item list-group-item-light">Latest Posts</li>
          <li class="list-group-item list-group-item-light">Announcements</li>
          <li class="list-group-item list-group-item-light">Calendars</li>
          <li class="list-group-item list-group-item-light">etc</li>
        </ul>
      </p>
    </div>
  </div>
{% endblock sidebar %}

video_webapp/posts/templates/posts/post_confirm_delete.html
{% extends "posts/base.html" %}
{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset>
        <legend class="border-bottom mb-4">Delete Post</legend>
        <h2>Are you sure you want to delete the post "{{ object.title }}"?</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
        <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock content %}

video_webapp/posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block video %}
<div class="row">
  <!--Spacing-->
  <div class="col-md-1"></div>
  <!--Post Content-->
  <div class="col-md-8">
    {% if object.video %}
      <!--Video-->
      <video name="{{ object.video }}" controls width='100%'>
        <source src="{{ object.video.url }}"></source>
      </video>
    {% endif %}
    <!--Post Title-->
    <h2 class="article-title">{{ object.title }}</h2>
    <!--Post Description-->
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
          <small class="text-muted">{{ object.date_posted|date:"l, F dS, Y, P T" }}</small>
        </div>
        <p class="article-content break-words">{{ object.content }}</p>
        {% if object.author == user %}
        <!-- Update and Delete buttons -->
        <div>
          <a class="btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update Post</a>
          <a class="btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete Post</a>
        </div>
        {% endif %}
      </div>
    </article>
    <!--Comment Section-->
    <div id="comment-list">
      <!--Comments Title-->
      <div class="row">
        <div class="col-md-12">
            <legend class="border-bottom mb-4">Comments ({{ page_obj.paginator.count }}) </legend> 
        </div>
      </div>
      <!--New Comment-->
        <!--New Comment Button-->
        <div id='newcomment-toggle-button1'>
          <button class="btn btn-outline-info" onclick="hideToggleDual('newcomment-toggle-button1','newcomment-toggle-button2')">New Comment</button>
        </div>
        <!--New Comment Form, initially hidden-->
        <div class="row" id='newcomment-toggle-button2' style="display:none">
          <div class="row">
            <!--Spacing-->
            <div class="col-md-1"></div>
            <div class="col-md-8">
              <form method="post" class='create-comment-form' value=''>
                {% csrf_token %}
                {{ comment_form|crispy }}
                <button class="btn btn-outline-success" type="submit">Add New Comment</button>
                <a class="btn btn-outline-secondary" onclick="hideToggleDual('newcomment-toggle-button1','newcomment-toggle-button2')">Cancel</a>
              </form>
            </div>
          </div>
        </div>
      <!--Spacing-->
      <div class="row">
        <div class="col-md-12">
          <legend class="mb-4"></legend> 
        </div>
      </div>
      <!--Comment list-->
      {% include 'posts/comment_page.html' %}
      <!--End Comments-->  
    </div>
  </div>
</div>
{% endblock video %}

video_webapp/posts/templates/posts/post_form.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset>
        <legend class="border-bottom mb-4">New Post</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-success" type="submit">Post</button>
        <a class="btn btn-outline-secondary" href="{% url 'posts-home' %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock content %}

video_webapp/posts/templates/posts/post_home.html
{% extends "posts/post_list.html" %}
{% block post %}
{% if user.is_authenticated %}
  <a class="btn btn-outline-info btn-lg" href="{% url 'post-create' %}">New Post</a>
  <div class="row">
    <div class="col-md-12">
      <legend class="mb-4"></legend> 
    </div>
  </div>
{% endif %}
{% endblock post %}

video_webapp/posts/templates/posts/post_list.html
{% extends "posts/base.html" %}
{% block content %}
  {% block post %}{% endblock %}
  {% for post in posts %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">{{ post.date_posted|date:"l, F dS, Y, P T" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
        {% if post.video %}
          <a href="{% url 'post-detail' post.id %}">
            <img src="{{ post.video_thumbnail.url }}" width="160" height="90">
          </a>
        {% endif %}
        <p class="article-content break-words">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}
  {% if is_paginated %}

    <!-- Add prev and first links if not already on first -->
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    <!-- Add in pages around the current page -->
    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>    
      {% endif %}
    {% endfor %}

    <!-- Add in the last if not at the end already -->
    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}
{% endblock content %}
{% block sidebar %}
  <!-- <div class="col-md-3">
    <div class="content-section">
      <h3>Our Sidebar</h3>
      <p class='text-muted'>You can put any information here you'd like.
        <ul class="list-group">
          <li class="list-group-item list-group-item-light">Latest Posts</li>
          <li class="list-group-item list-group-item-light">Announcements</li>
          <li class="list-group-item list-group-item-light">Calendars</li>
          <li class="list-group-item list-group-item-light">etc</li>
        </ul>
      </p>
    </div>
  </div> -->
{% endblock sidebar %}

video_webapp/posts/templates/posts/shell.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS https://getbootstrap.com/docs/4.3/getting-started/introduction/ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/main.css' %}">

    {% if title %}
      <title>{{ title }} - Local App</title>
    {% else %}
      <title>Local App</title>
    {% endif %}

    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!--Header Scripts-->
    <script src="{% static 'js/headerscripts.js' %}"></script>

  </head>
  <body>
    {% block body %}{% endblock %}
  </body>
</html>

video_webapp/posts/templates/posts/user_posts.html
{% extends "posts/post_list.html" %}
{% block post %}
  <h2 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
{% endblock post %}